name: Count Lines of Code

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@6
        with:
          options: --json --report-file=loc-meta.json
